### PR TITLE
Add penalty for challengers

### PR DESCRIPTION
**Pull request by KwanMan**
It's a bit shit right now because people can bombard you with challenges to push your score down. The challenger should also get the penalty so they are more inclined to actually play that match quickly or remove the challenge

### CODE REVIEW

**Comment by KidkArolis** [comment]
I think this might be a bit divisive :) I think Alz did the algo like that on purpose, so you can shoot down people from the top of the list if they don't play enough variety of games.

I would possibly remove the challenger feature, instead reward variety, perhaps. Having said that, Alz said the feature is being used, so perhaps it's all good as is.

Re this PR, I think it's better as is - don't punish the challenger.

**Comment by KwanMan** [comment]
The feature is just too easily abused, you can challenge someone, they play you, then you challenge them again and they will permanently have a penalty.

I like making sure people are playing a diverse enough set of players though. How about we multiply the vitality with another metric:

- For the last 8 weeks, we take the player who has played the largest number of unique opponents
- Then for everyone else, if they have played less than half this, we start punishing them on a sliding scale same as we do vitality

For example:

- yuriy plays the most diverse set of people in the past 8 weeks: 20
- alz plays 12 different opponents: 12/20 = 0.6 which is over 50% so vitality is not affected
- gio only plays 6 opponenets: 6/20 = 0.3 which is under 0.5 so we reduce the vitality
  - 1 / ((required-opponents)-(played opponents))
  - 1 / ((0.5*20) - 6) = 0.25 so hist vitality to reduces to a quarter

This way we punish people for both not playing, and also not playing enough different opponents

@alanclarke @KidkArolis

**Comment by alanclarke** [comment]
Thanks tman!

The vitality thing wasn’t very effective at making people play more. It was demotivating because you couldn’t affect the score very quickly. We changed it to only affect people who haven’t played for a significant period, which is better but I suspect the impact is cleaner rankings rather than more games.

I think there are better ways to encourage diversity of games than a more complicated penalty system: E.g.
- feature to give you a random opponent
- foosbot proposing a random game every day around lunchtime
- tournament orchestration

Re challenges, yeah I don’t think the challenger should be penalised, the point of the penalty was that if someone challenges you and you are too chicken to play them foosbot calls you out and penalises you

Re that form of abuse, that’s a good point although we could also prevent that with a simple rule, e.g. if someone challenged you and you played them, they’re not allowed to challenge you again for a while

**Comment by alanclarke** [comment]
By the way you can also challenge them back, so they also get the penalty, although it’s a bit of a hack I guess

**Comment by KwanMan** [comment]
Yea challenging back is what people have been doing, but that's just turned into a pile of hell

I think the most immediate/easiest thing to add for now is to limit challenges to the same person to 1 per week (or 1 per day? just so people don't constantly rechallenge after a game)

I also think the penalty could be done better though, maybe only give the person a penalty if they havent responded to a challenge in 1 day

**Pull request closed without merging**
